rosrun mmseq_utils plot_benchmark_result_semi_static_reactive.py -f $MOBILE_MANIPULATION_CENTRAL_BAG_DIR/ral25/semi_static_wholebody/1.9m --base_path
rosrun mmseq_utils plot_benchmark_result_semi_static_reactive.py -f $MOBILE_MANIPULATION_CENTRAL_BAG_DIR/ral25/semi_static_wholebody/htmpc_vs_stmpc_organized --htmpc_vs_stmpc
rosrun mmseq_utils plot_benchmark_result_semi_static_reactive.py -f $MOBILE_MANIPULATION_CENTRAL_BAG_DIR/ral25/semi_static_wholebody/2.4m_gamma_vary --sdf_distance

